### PR TITLE
docs: add nginx readme

### PR DESCRIPTION
**Pull request by Nischay-Pro**

### CODE REVIEW

**Comment by aero31aero** [comment]
Merged the nginx docs. Need to discuss the Google Analytics strategy a little. Should we place the analytics on the `index.jade`? Because that file would only be loaded once but if Google Analytics supports reading state changes from the History API, then this should work. Have you manually tested this?

**Comment by Nischay-Pro** [comment]
Google performs only 1 check per click. Sending multiple requests via dynamic ones will cause Google to ban us.

**Comment by Nischay-Pro** [comment]
APPROVE THE HTTPS ONE. I need to test https.

**Comment by aero31aero** [comment]
@Nischay-Pro I'll do a manual merge again. Wait a few minutes.

**Comment by Nischay-Pro** [comment]
cool

**Comment by aero31aero** [comment]
Closing this PR because the Analytics need to be rethought in our single page scenario. Other two commits have been merged.

**Pull request closed without merging**
