### PR TITLE
Modules

### PR DESCRIPTION
**Pull request by FoolDresden**
Added module-home to home css and home jade files. Add module about to about css. Could not find about jade. Does it exist?

### CODE REVIEW

**Comment by FoolDresden** [comment]
DO NOT merge. There are some mistakes.

**Comment by aero31aero** [comment]
Okay. Holding the review till you say you're done.

**Comment by aero31aero** [comment]
I merged the homepage commits as be1cbca and removed those commits, along with the login page and your commit-revert cycles, from this PR. This leaves the events page, which I'm reviewing now.

**Comment by aero31aero** [comment]
Closing as an alternate version already merged as #281

**Pull request closed without merging**
