### PR TITLE
Added Coveralls. Need to test though.

### PR DESCRIPTION
**Pull request by Nischay-Pro**

### CODE REVIEW

**Comment by Nischay-Pro** [comment]
Prepare to fail miserably. Someone fix this. 🥉

**Comment by Nischay-Pro** [comment]
47.541% gg :3

**Comment by Nischay-Pro** [comment]
Chalo Coverage is working and Travis is pushing to coverage after PUSH.

**Comment by Nischay-Pro** [comment]
Btw. If you guys don't know travis pr is previous travis config
and travis push is after push the new travis config.

**Comment by aero31aero** [comment]
@Nischay-Pro Umm... I guess we could take a break on the automation. We just have 3 unit tests and a linter.

**Comment by Nischay-Pro** [comment]
Sigh. I was planning to add 7 more tools. :'(

**Pull request closed without merging**
