### PR TITLE
[WIP] Configure nodemailer

### PR DESCRIPTION
**Pull request by sohailrajdev97**

### CODE REVIEW

**Comment by Nischay-Pro** [comment]
Why not use the official Google Node.JS packages instead of NodeMailer.

Official Packages
- googleapis
- google-auth-library

**Comment by Nischay-Pro** [comment]
Wait why are we even using nodemailer? Have we tested the working of it with Google API?

**Comment by aero31aero** [comment]
Consider this merge as temporary given the blocking nature of cyberoam. We can only test the code in prod and that's what Abhilash has been working on.

**Comment by Nischay-Pro** [comment]
But why are we building the application with cyberroam in mind. Don't you use a VPN or Mobile data while coding?

_Sent from my Samsung SM-N930F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by aero31aero** [comment]
Merge wasn't my decision. Just explaining @rogeredthat 's reasoning here. :smile:

**Comment by Nischay-Pro** [comment]
Sigh

**Pull request merged**
